### ISSUE TITLE
 resource types are not supported for resource import: AWS::CloudFormation::WaitConditionHandle

### ISSUE THREAD

**Issue by JahnKhan** [khchan123/stable-diffusion-webui-ec2#1]
hello,
i am trying to deploy the template on aws but in cloudformation during import i get this
`The following resource types are not supported for resource import: AWS::CloudFormation::WaitConditionHandle,AWS::CloudFormation::WaitCondition`

**Comment by khchan123** [comment]
It appears that you are trying to use the Import feature in CloudFormation to launch the stack.
The Import feature does not support some of the AWS resources as quoted in the message.

Can you please try again to launch the stack but choose 'standard' instead of 'import resources'?
